import schedule
import os.path
import yaml
import time
import subprocess

if os.path.exists('config.yaml'):
    configfile = 'config.yaml'
    print("found custom config")
else:
    configfile = 'defaultconfig.yaml'
    print("no custom config found, load default")

with open(configfile, 'r') as f:
    try:
        config = yaml.safe_load(f)
        print("config loaded")
    except yaml.YAMLError as exc:
        print(exc)

sync_down = "rclone sync {rname}:{rpath}/finance.ledger data/".format(rname=config['remotename'], rpath=config['remotepath'])
sync_up = "rclone sync data/finance.ledger {rname}:{rpath}".format(rname=config['remotename'], rpath=config['remotepath'])

def check_for_trans():
    today = time.strftime("%d") 
    for t in config['transactions']:
        if t['dom'] == today:
            print("Found transaction: {rec}".format(t['rec']))
            write_transaction(t)

def write_transaction(t):
    r = subprocess.call(sync_down, shell=True)
    
    ledgerfile = open('data/finance.ledger', 'a')
    ledgerfile.write("{date} * {rec}\n".format(date=time.strftime("%Y/%m/%d", rec=t['rec'])))
    ledgerfile.write("    ; generated by scheduledledger\n")
    ledgerfile.write("    {fromacc}\n".format(fromacc=t['from']))
    ledgerfile.write("    {toacc}    {amount} {cur}\n\n".format(toacc=t['to'], amount=t['amount'], cur=config['currency']))
    ledgerfile.close()

    r = subprocess.call(sync_down, shell=True)
    print("wrote transaction to ledgerfile")

schedule.every().day.at("12:00").do(check_for_trans)

while True:
    schedule.run_pending()
    time.sleep(1)
    

